name: Build libraries

on:
  pull_request:
    branches: [ main, rc/*, feat/*, dev ]
    types: [ opened, ready_for_review ]
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Get dependencies
        shell: bash
        run: |
         go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
          fi

      - name: Build libbls (Linux)
        if: runner.os == 'Linux'
        run: | 
          cd ./libraries/libbls
          go build -buildmode=c-shared -o $GITHUB_WORKSPACE/libbls.so .

      - name: Build libbls (MacOS)
        if: runner.os == 'macOS'
        run: | 
          cd ./libraries/libbls
          go build -buildmode=c-shared -o $GITHUB_WORKSPACE/libbls.dylib .

      - name: Build libbls (Windows)
        shell: bash
        if: runner.os == 'Windows'
        run: | 
          cd ./libraries/libbls
          go build -buildmode=c-shared -o $GITHUB_WORKSPACE/libbls.dll .

      - name: Save artifacts
        uses: actions/upload-artifact@v5
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            libbls.so
            libbls.dylib
            libbls.dll
          if-no-files-found: error

  attach-on-release:
    if: github.event_name == 'release'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Download all workflow artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} $(find ./artifacts -type f)
